### ISSUE TITLE
What do you think about inlining best practice code examples and making each item linkable?

### ISSUE THREAD

**Issue by balvig** [cookpad/guides#68]
Ie something like this ([work in progress](https://github.com/cookpad/guides/tree/linkable/best-practices)):

![guides_best-practices_at_linkable_ _cookpad_guides](https://user-images.githubusercontent.com/104138/33471404-8f373fa2-d6b0-11e7-9de6-5e71a21912a7.png)

## Motivation

- I often find myself wanting to link to a specific item
- Having both reference links and links to code samples on the same item would be fiddly
- Maintaining code samples separately has always been a bit awkward

It will lose some of the compactness of the current version of course, but wondering what people think?

**Comment by davidstosik** [comment]
That looks like the [Ruby](https://github.com/bbatsov/ruby-style-guide) or [Rails](https://github.com/bbatsov/rails-style-guide) community-driven style guides!

Personally I like it. Often want to link to a specific item too. 👍

**Comment by JuanitoFatas** [comment]
I am +1 since I was a proponent for having links of everything in https://github.com/cookpad/guides/pull/23.

**Comment by Knack** [comment]
:+1: I like this format much more. In addition, it is easier to add small descriptions or explanations.

**Comment by sebasoga** [comment]
+1

**Comment by balvig** [comment]
Thanks for the positive feedback! Will open a PR then 👍
