### ISSUE TITLE
Proposal for re-arranging guides

### ISSUE THREAD

**Issue by lewispb** [cookpad/guides#91]
Currently our guide is arranged into three folders:

- Workflow
- Code Review
- Best Practices
  - BEM

Primarily, however, this guide is used to refer to our agreed Ruby / Rails / JS / CSS style.

How about we move Workflow and Code Review elsewhere? Perhaps to the web chapter?

And then to make it easier to find the guide we are looking for we split out our current guides like this:

- Ruby
  - README.md
- Rails
  - README.md
  - rake.md
  - testing.md
  - i18n.md
- Javascript
  - README.md
- CSS
  - README.md

**Comment by balvig** [comment]
Totally on board with this, as the doc was getting kind of hard to edit and I'm currently working on a document to capture the non-code parts of how we work 👍
